service: import-service
frameworkVersion: '3'


provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
    AWS_BUCKET_NAME: 'import-service-epam-bucket'
    AWS_FOLDER_NAME: 'uploaded'
    REGION: 'eu-west-1'
    SQS_URL: https://sqs.eu-west-1.amazonaws.com/984152597152/catalogItemsQueue

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::import-service-epam-bucket"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::import-service-epam-bucket/*"
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: "arn:aws:sqs:eu-west-1:984152597152:catalogItemsQueue"

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    dotenvVars: ${file(configs.js)}

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
          authorizer:
            name: 'authorization-service-dev-basicAuthorizer'
            type: 'token'
            arn: 'arn:aws:lambda:eu-west-1:984152597152:function:authorization-service-dev-basicAuthorizer'
            resultTtlInSeconds: 0
            identitySource: 'method.request.header.Authorization'


  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: ${self:provider.environment.AWS_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
                - prefix: uploaded/
          existing: true

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          "gatewayresponse.header.Access-Control-Allow-Origin": "'*'"
          "gatewayresponse.header.Access-Control-Allow-Headers": "'*'"
        ResponseType: 'DEFAULT_4XX'
        RestApiId: 
          Ref: "ApiGatewayRestApi"
